species: "scientific species name"
reference: "/path/to/reference.fasta"
region:
  Region1:
    left_flank: "Flanking gene"
    left_flank_local: "/path/to/left.fasta"
    right_flank: "Flanking gene"
    right_flank_local: "/path/to/right.fasta"
    cDNA_library: "/path/to/cDNA_reference.fasta" 
    gDNA_library: "/path/to/gDNA_references.fasta"
  Region2:
    left_flank: "Flanking gene"
    left_flank_local: "/path/to/left.fasta"
    right_flank: "Flanking gene"
    right_flank_local: "/path/to/right.fasta"
    cDNA_library: "/path/to/cDNA_reference.fasta"
