species: "macaca mulatta"
region:
  KIR:
    left_flank: "FCAR"
    right_flank: "LILRA6"
    library: "references/mamu_kir_gen_2501.fasta" 
    minimap2: "-cx splice:hq -G16k"
    blast: "-word_size 7"
  LILR:
    left_flank: "RPS9"
    right_flank: "FCAR"
    library: "references/LILR_cDNA_library.fasta"
    minimap2: "-cx splice:hq -G16k"
    blast: "-word_size 7"
