species: "species name"
reference:
  reference_name:
    accession_number: "NCBI accession"
    genome: "/path/to/local/reference/genomic.fna"
    gff: "/path/to/local.gff"
    chr_info: "/path/to/local/chr_info_file"
region:
  Region1:
    left_flank: "Flank1"
    right_flank: "Flank2"
    library: "/path/to/references/annotation.fasta" 
    minimap2: "-cx splice:hq -G16k"
    blast: "-word_size 7"
  Region2:
    left_flank: "Flank2"
    right_flank: "Flank2"
    library: "/path/to/references/annotation2.fasta" 
    minimap2: "-cx splice:hq -G16k "
    blast: "-word_size 7"
nanopore:
  Sample_1:
    - "/path/to/local/Sample_1/nanopore/fastq1"
  Sample_2:
    - "/path/to/local/Sample_2/nanopore/fastq1"
pacbio:
  Sample_1:
    - "/path/to/local/Sample_1/pacbio/bam1"
  Sample_2:
    - "/path/to/local/Sample_2/pacbio/bam1"

