species: "Macaca mulatta"
reference:
  GCF_003339765.1:
    dataset: "GCF_003339765.1"
    genome: "/path/to/local/reference/GCF_003339765.1_Mmul_10_genomic.fna.gz"
    gff: "genomes/GCF_003339765.1/GCF_003339765.1.gff"
    info: "/path/to/local/info_file"
region:
  KIR:
    left_flank: "FCAR"
    right_flank: "LILRA6"
    library: "references/mamu_kir_gen_2501.fasta" 
    minimap2: "-cx splice:hq -G16k"
    blast: "-word_size 7"
  MHC:
    left_flank: "KIFC1"
    right_flank: "GABBR1"
    library: "references/mamu_mhc_gen_2501.fasta" 
    minimap2: "-cx splice:hq -G16k "
    blast: "-word_size 7"
busco: "primates_odb10"
nanopore:
  EAW:
    - "/mnt/CGRBackup/EAW/nanopore/EAW_SRE25_2-8-2023/EAW_SRE25_2-8-2023_fastq"
    - "/mnt/CGRBackup/EAW/nanopore/EAW_SRE25_26-07-23/EAW_SRE25_26-07-23_fastq"
pacbio:
  EAW:
    - "/mnt/CGRBackup/EAW/pacbio/1_C01/reads_test"
